import { WebSocket } from 'ws';
import { ISymbolTickerStreamPayload } from '../datasources/binance/index.types';
import pubsub from '../external-libs/pubsub';

export class BinanceAPIDataSource {
  private readonly BINANCE_MARKET_STREAMS_URL = 'wss://fstream.binance.com';

  public startSymbolTickerStream(symbol: string, retry = 0) {
    symbol = symbol.toUpperCase();
    if (retry > 3) {
      console.error(`Failed to stream ${symbol} ticker`);
      return;
    }
    const binancePriceStream = new WebSocket(`${this.BINANCE_MARKET_STREAMS_URL}/ws/${symbol?.toLowerCase()}@ticker`, {
      timeout: 5000
    });
    binancePriceStream.on('open', () => {
      console.log(`${symbol} ticker stream connected`);
    });
    binancePriceStream.on('error', () => {
      console.error(`${symbol} ticker stream error`);
    });
    binancePriceStream.on('close', () => {
      console.error(`${symbol} ticker stream close`);
      console.error(`Retried to stream ${symbol}: ${retry}`);
      setTimeout(() => this.startSymbolTickerStream(symbol, retry + 1), 5000);
    });
    binancePriceStream.on('message', (payload: string) => this.processPriceStream(payload));
  }

  private processPriceStream(_payload: string) {
    const payload: ISymbolTickerStreamPayload = JSON.parse(_payload);
    try {
      if (payload?.s?.startsWith('DODOX')) {
        payload.s = payload?.s?.replace('DODOX', 'DODO');
      }
      console.log('payload: %j', payload);
      pubsub.publish('NOTIFY_PRICE_DATA', {
        data: payload
      });
      pubsub.publish('NOTIFY_PRICE_DATA_BY_LIST', {
        data: payload
      });

      return true;
    } catch (error) {
      console.error(error);
      return null;
    }
  }
}

const run = async (symbols: string[]) => {
  symbols.forEach(async (symbol) => {
    await new BinanceAPIDataSource().startSymbolTickerStream(symbol);
  });
};

const symbols = [
  'BTCUSDT',
  'ETHUSDT',
  'BCHUSDT',
  'XRPUSDT',
  'EOSUSDT',
  'LTCUSDT',
  'TRXUSDT',
  'ETCUSDT',
  'LINKUSDT',
  'XLMUSDT',
  'ADAUSDT',
  'XMRUSDT',
  'DASHUSDT',
  'ZECUSDT',
  'XTZUSDT',
  'BNBUSDT',
  'ATOMUSDT',
  'ONTUSDT',
  'IOTAUSDT',
  'BATUSDT',
  'VETUSDT',
  'NEOUSDT',
  'QTUMUSDT',
  'IOSTUSDT',
  'THETAUSDT',
  'ALGOUSDT',
  'ZILUSDT',
  'KNCUSDT',
  'ZRXUSDT',
  'COMPUSDT',
  'OMGUSDT',
  'DOGEUSDT',
  'SXPUSDT',
  'LENDUSDT',
  'KAVAUSDT',
  'BANDUSDT',
  'RLCUSDT',
  'WAVESUSDT',
  'MKRUSDT',
  'SNXUSDT',
  'DOTUSDT',
  'DEFIUSDT',
  'YFIUSDT',
  'BALUSDT',
  'CRVUSDT',
  'TRBUSDT',
  'YFIIUSDT',
  'RUNEUSDT',
  'SUSHIUSDT',
  'SRMUSDT',
  'BZRXUSDT',
  'EGLDUSDT',
  'SOLUSDT',
  'ICXUSDT',
  'STORJUSDT',
  'BLZUSDT',
  'UNIUSDT',
  'AVAXUSDT',
  'FTMUSDT',
  'HNTUSDT',
  'ENJUSDT',
  'FLMUSDT',
  'TOMOUSDT',
  'RENUSDT',
  'KSMUSDT',
  'NEARUSDT',
  'AAVEUSDT',
  'FILUSDT',
  'RSRUSDT',
  'LRCUSDT',
  'MATICUSDT',
  'OCEANUSDT',
  'CVCUSDT',
  'BELUSDT',
  'CTKUSDT',
  'AXSUSDT',
  'ALPHAUSDT',
  'ZENUSDT',
  'SKLUSDT',
  'GRTUSDT',
  '1INCHUSDT',
  'BTCBUSD_210129',
  'BTCBUSD_210226',
  'BTCBUSD',
  'AKROUSDT',
  'DOTECOUSDT',
  'CHZUSDT',
  'SANDUSDT',
  'ANKRUSDT',
  'LUNAUSDT',
  'BTSUSDT',
  'BTCUSDT_210326',
  'ETHUSDT_210326',
  'LITUSDT',
  'UNFIUSDT',
  'DODOUSDT',
  'REEFUSDT',
  'RVNUSDT',
  'SFPUSDT',
  'XEMUSDT',
  'BTCSTUSDT',
  'COTIUSDT',
  'CHRUSDT',
  'MANAUSDT',
  'ALICEUSDT',
  'BTCUSDT_210625',
  'ETHUSDT_210625',
  'HBARUSDT',
  'ONEUSDT',
  'LINAUSDT',
  'STMXUSDT',
  'DENTUSDT',
  'CELRUSDT',
  'HOTUSDT',
  'MTLUSDT',
  'OGNUSDT',
  'BTTUSDT',
  'NKNUSDT',
  'SCUSDT',
  'DGBUSDT',
  '1000SHIBUSDT',
  'ICPUSDT_SETTLED',
  'BAKEUSDT',
  'GTCUSDT',
  'ETHBUSD',
  'BTCUSDT_210924',
  'ETHUSDT_210924',
  'BTCDOMUSDT',
  'KEEPUSDT',
  'TLMUSDTSETTLED',
  'BNBBUSD',
  'ADABUSD',
  'XRPBUSD',
  'IOTXUSDT',
  'DOGEBUSD',
  'AUDIOUSDT',
  'RAYUSDT',
  'C98USDT',
  'MASKUSDT',
  'ATAUSDT',
  'SOLBUSD',
  'FTTBUSD',
  'DYDXUSDT',
  '1000XECUSDT',
  'GALAUSDT',
  'BTCUSDT_211231',
  'ETHUSDT_211231',
  'CELOUSDT',
  'ARUSDT',
  'KLAYUSDT',
  'ARPAUSDT',
  'NUUSDT',
  'CTSIUSDT',
  'LPTUSDT',
  'ENSUSDT',
  'BTCUSDT_220325',
  'ETHUSDT_220325',
  'PEOPLEUSDT',
  'ANTUSDT',
  'ROSEUSDT',
  'DUSKUSDT',
  '1000BTTCUSDT',
  'FLOWUSDT',
  'IMXUSDT',
  'API3USDT',
  'ANCUSDT',
  'GMTUSDT',
  'APEUSDT',
  'BTCUSDT_220624',
  'ETHUSDT_220624',
  'BNXUSDTSETTLED',
  'WOOUSDT',
  'FTTUSDT',
  'JASMYUSDT',
  'DARUSDT',
  'GALUSDT',
  'LUNABUSD',
  'AVAXBUSD',
  'NEARBUSD',
  'GMTBUSD',
  'APEBUSD',
  'GALBUSD',
  'FTMBUSD',
  'DODOBUSD',
  'ANCBUSD',
  'GALABUSD',
  'TRXBUSD',
  '1000LUNCBUSD',
  'LUNA2BUSD',
  'OPUSDT',
  'DOTBUSD',
  'TLMBUSD',
  'ICPBUSD',
  'BTCUSDT_220930',
  'ETHUSDT_220930',
  'WAVESBUSD',
  'LINKBUSD',
  'SANDBUSD',
  'LTCBUSD',
  'MATICBUSD',
  'CVXBUSD',
  'FILBUSD',
  '1000SHIBBUSD',
  'LEVERBUSD',
  'ETCBUSD',
  'LDOBUSD',
  'UNIBUSD',
  'AUCTIONBUSD',
  'INJUSDT',
  'STGUSDT',
  'FOOTBALLUSDT',
  'SPELLUSDT',
  '1000LUNCUSDT',
  'LUNA2USDT',
  'AMBBUSD',
  'PHBBUSD',
  'LDOUSDT',
  'CVXUSDT',
  'BTCUSDT_221230',
  'ETHUSDT_221230',
  'ICPUSDT',
  'APTUSDT',
  'QNTUSDT',
  'APTBUSD',
  'BLUEBIRDUSDT',
  'ETHUSDT_230331',
  'BTCUSDT_230331',
  'FETUSDT',
  'AGIXBUSD',
  'FXSUSDT',
  'HOOKUSDT',
  'MAGICUSDT',
  'TUSDT',
  'RNDRUSDT',
  'MINAUSDTSETTLED',
  'HIGHUSDT',
  'MINAUSDT',
  'ASTRUSDT',
  'AGIXUSDT',
  'PHBUSDT',
  'GMXUSDT',
  'CFXUSDT',
  'STXUSDT',
  'COCOSUSDT',
  'BNXUSDT',
  'ACHUSDT',
  'SSVUSDT',
  'CKBUSDT',
  'PERPUSDT',
  'TRUUSDT',
  'LQTYUSDT',
  'USDCUSDT',
  'IDUSDT',
  'ARBUSDT',
  'ETHUSDT_230630',
  'BTCUSDT_230630',
  'JOEUSDT',
  'TLMUSDT',
  'AMBUSDT',
  'LEVERUSDT',
  'RDNTUSDT',
  'HFTUSDT',
  'XVSUSDT',
  'ETHBTC',
  'BLURUSDT',
  'EDUUSDT',
  'IDEXUSDT',
  'SUIUSDT',
  '1000PEPEUSDT',
  '1000FLOKIUSDT',
  'UMAUSDT',
  'RADUSDT',
  'KEYUSDT',
  'COMBOUSDT',
  'NMRUSDT',
  'BTCUSDT_230929',
  'ETHUSDT_230929',
  'MAVUSDT',
  'MDTUSDT',
  'XVGUSDT',
  'WLDUSDT',
  'PENDLEUSDT',
  'ARKMUSDT',
  'AGLDUSDT',
  'YGGUSDT',
  'DODOXUSDT',
  'BNTUSDT',
  'OXTUSDT',
  'SEIUSDT',
  'BTCUSDT_231229',
  'ETHUSDT_231229',
  'CYBERUSDT',
  'HIFIUSDT',
  'ARKUSDT',
  'FRONTUSDT',
  'GLMRUSDT',
  'BICOUSDT',
  'BTCUSDT_240329',
  'ETHUSDT_240329',
  'STRAXUSDT',
  'LOOMUSDT',
  'BIGTIMEUSDT',
  'BONDUSDT',
  'ORBSUSDT',
  'STPTUSDT',
  'WAXPUSDT',
  'BSVUSDT',
  'RIFUSDT',
  'POLYXUSDT',
  'GASUSDT',
  'POWRUSDT',
  'SLPUSDT',
  'TIAUSDT',
  'SNTUSDT',
  'CAKEUSDT',
  'MEMEUSDT',
  'TWTUSDT',
  'TOKENUSDT',
  'ORDIUSDT',
  'STEEMUSDT',
  'BADGERUSDT',
  'ILVUSDT',
  'NTRNUSDT',
  'MBLUSDT'
];

run(symbols);
